### PR TITLE
Commit mock pagination userscript.

### PR DESCRIPTION
**Pull request by davidmear**

### CODE REVIEW

**Comment by davidmear** [comment]
There's some more description in [this metatalk post](https://metatalk.metafilter.com/24893/Mock-pagination-userscript).

**Comment by sarahtisdale** [comment]
I tried it out on one of the huge political threads.  Pretty cool!   Makes it manageable.

**Comment by sarahtisdale** [comment]
We'll also need to add it to "userscripts/README.md".

**Review by sarahtisdale — APPROVED** [review]
Approving!  I'll make a separate commit to update userscripts/README.md.

**Comment by davidmear** [comment]
Thanks!

**Pull request merged**
