### PR TITLE
A basic site for this repository

### PR DESCRIPTION
**Pull request by emanuelfeld**
Shows all the README tables on one page.

Might want to change this repo to mefiscripts.github.io

### CODE REVIEW

**Comment by emanuelfeld** [comment]
Looks like this 
screen shot 2018-01-04 at 7 44 39 pm
screen shot 2018-01-04 at 7 45 38 pm

**Review by davekaufman — COMMENTED** [review]
site design looks ok to me, though maybe we should go for mefi colors?  Also not sure about the removal of the "Where applicable links to the source code on Github have also been included" from the `extensions/README.md`, as that notation seems worthwhile to me.  

With those (minor) quibbles of mine, I'm commenting and not approving.  If nobody else chimes in, approve.

**Comment by emanuelfeld** [comment]
The green border is one of the MeFi colors, but I didn't want to give the impression that the site was an official one. I removed that line because the source is included for every script in the repository, so it didn't seem of note. I'm fine with people futzing with the css further.

**Review by jcushman — APPROVED** [review]
This looks good to me, and I like the simplified language in various places. Let's try it!

**Pull request merged**
